name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # do not cancel any pending/running jobs
      fail-fast: false
      matrix:
        maven: [ '3.5.4', '3.6.3', '3.8.1', '3.8.4', '3.8.5' ]
    name: Maven ${{ matrix.maven }}
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 8
          maven-version: ${{ matrix.maven }}
      - run: mvn clean package